emersonmellado/nodebcjan6

first-site.md

I have fixed the typo in the index.html file regarding linking to the external css.

Fixing the typo

---

first-site.md

Typo found in link tag referencing css file as well as in the comments.

Fixed typo in first-site file

---

first-site.md

Changing style.css to styles.css throughout the file.

Reverting back to original state with styles.css

---

exercises/css/ex_6.md

It was "Applyt" and I replaced for apply =)

Just  a writing error

---

html.md

just spelling correction from manualy to manually.

spelling correction

---

exercises/html/ex_12.md

Typo Error

---

html.md

Changed definening to defining

Change spelling

---

html.md

Altered sentence flow and structure as well as deleted punctuation for consistency

Changed grammar

---

html.md

Changed identation to indentation and changed sentence structure

Grammar and spelling typo

---

exercises/js/ex_58.md

Spell corretion

---

exercises/css/ex_16.md

The image shows numeric values, then square bullets and finally the snow image. However, the structure of your html is different, there is a <ul>, then a <ol> and then <ul> with class decorated. You can either change the image or you can change the ordering of the <ul> and <ol>.  I have changed the code to match the image by switching <ul> with <ol>.

The image does not match the html structure

---

exercises/js/ex_30.md

corrected square perimeter link to square areahttps://www.mathopenref.com/squarearea.html

added the link to square area

---

css.md

Just to pull more pull requests :)

Some grammar correction

---

javascript.md

The 'nombre' is not defined and I believe you meant name

Fixing variable name

---

exercises/css/ex_22.md

I say possible because I might have misunderstood it.

Possible property correction

---

css.md

Your link to MDN position is in your language which would be ok if I could understand but sadly I don't. :( I changed the link to the English version.

Updating the link to MDN position

---

exercises/js/ex_2.md

Corrected word

---

javascript.md

Changed "greater" to "less" to match the note below: * The age condition is **false** but as we use the not operator it will be **true**

Change of conditional operator syntax.

---

javascript.md

Spanish word changed to English

---

exercises/js/ex_63.md

Typo error for output

---

javascript.md

#Typo error
